import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="flex flex-col min-h-screen">
        <header className="bg-slate-900 text-white py-4 px-10 flex justify-between items-center gap-x-5 w-full">
          <h1 className="mr-4 text-2xl font-bold">Quiz App</h1>
          <nav>
            <ul className="font-semibold flex gap-x-6">
              <li>
                <Link href="/" className="bg-slate-700 rounded-2xl p-2">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/question" className="bg-slate-700 rounded-2xl p-2">
                  Question
                </Link>
              </li>
              <li>
                <Link href="/state" className="bg-slate-700 rounded-2xl p-2">
                  State
                </Link>
              </li>
              <li>
                <Link href="/quiz" className="bg-slate-700 rounded-2xl p-2">
                  Quiz
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="flex-1 pb-5">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
